# Generated by Django 5.1.6 on 2025-04-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
